test(ci): test working directory

diff --git a/.github/workflows/front_workflow.yml b/.github/workflows/front_workflow.yml
--- a/.github/workflows/front_workflow.yml
+++ b/.github/workflows/front_workflow.yml
@@ -35,7 +35,7 @@ jobs:
             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
             exit 0
           else
-            echo "Unable to determine package manager" >&2
+            echo "Unable to determine package manager $(ls ${{ github.workspace }})" >&2
             exit 1
           fi
       - name: Setup Node
